{
 "title": "EV Charging Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "Chargers",
    "label": "Charger",
    "query": "import \"influxdata/influxdb/v1\"\nv1.tagValues(\n    bucket: v.bucket,\n    tag: \"name\",\n    predicate: (r) => true,\n    start: -10s\n)"
   }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"BucketTFG\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"stationA\")\n  |> filter(fn: (r) => contains( value: r[\"name\"], set: ${Chargers:json}))\n  |> filter(fn: (r) => r[\"_field\"] == \"vehicleID\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: true)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Current Vehicle Bill",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"BucketTFG\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"stationA\")\n  |> filter(fn: (r) => contains( value: r[\"name\"], set: ${Chargers:json}))\n  |> filter(fn: (r) => r[\"_field\"] == \"energyBill\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: true)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Chargers Power",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"BucketTFG\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"stationA\")\n  //|> filter(fn: (r) => contains(value: r[\"name\"], set: ${Chargers:json}))\n  |> filter(fn: (r) => r[\"name\"] == \"Charger1\")\n  |> filter(fn: (r) => r[\"_field\"] == \"maxPower\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Electricity Price / kWh",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"BucketTFG\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"stationA\")\n  //|> filter(fn: (r) => contains(value: r[\"name\"], set: ${Chargers:json}))\n  |> filter(fn: (r) => r[\"name\"] == \"Charger1\")\n  |> filter(fn: (r) => r[\"_field\"] == \"price\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Average Waiting Time Today",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"BucketTFG\")\n  |> range(start: -1d)  // Selecciona el último día\n  |> filter(fn: (r) => r._measurement == \"stationAQueue\")\n  |> filter(fn: (r) => r._field == \"waitingTime1\" or r._field == \"vehicle1\")\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> group(columns: [\"vehicle1\"])\n  |> sort(columns: [\"_time\"], desc: true)\n  |> unique(column: \"vehicle1\")\n  |> group()\n  |> mean(column: \"waitingTime1\")\n  |> yield(name: \"mean_waiting_time_vehicle1\")\n"
    }
   ]
  },
  {
   "title": "Batery Level",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"BucketTFG\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"stationA\")\n  |> filter(fn: (r) => contains( value: r[\"name\"], set: ${Chargers:json}))\n  |> filter(fn: (r) => r[\"_field\"] == \"bateryLevel\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: true)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Waiting Queue",
   "type": "stat",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"BucketTFG\")\n  |> range(start: -30s)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"stationAQueue\")\n  |> filter(fn: (r) => r[\"_field\"] == \"waitingTime1\" or r[\"_field\"] == \"waitingTime2\" or r[\"_field\"] == \"waitingTime3\" or r[\"_field\"] == \"waitingTime4\" or r[\"_field\"] == \"waitingTime5\" or r[\"_field\"] == \"vehicle5\" or r[\"_field\"] == \"vehicle4\" or r[\"_field\"] == \"vehicle3\" or r[\"_field\"] == \"vehicle2\" or r[\"_field\"] == \"vehicle1\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Average waiting time last 5 days",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "query": "// Función que calcula la media de waitingTime1 para un rango de tiempo dado\naverageWaitingTime = (start, stop, day) => \n  from(bucket: \"BucketTFG\")\n    |> range(start: start, stop: stop)\n    |> filter(fn: (r) => r._measurement == \"stationAQueue\")\n    |> filter(fn: (r) => r._field == \"waitingTime1\" or r._field == \"vehicle1\")\n    |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n    |> group(columns: [\"vehicle1\"])\n    |> sort(columns: [\"_time\"], desc: true)\n    |> unique(column: \"vehicle1\")\n    |> group()\n    |> mean(column: \"waitingTime1\")\n    |> map(fn: (r) => ({r with day: day, mean: r.waitingTime1, media: \"media\"}))\n    |> keep(columns: [\"day\", \"mean\", \"media\"])\n\navgDay1 = averageWaitingTime(start: -1d, stop: now(), day: \"Today\")\navgDay2 = averageWaitingTime(start: -2d, stop: -1d, day: \"Yesterday\")\navgDay3 = averageWaitingTime(start: -3d, stop: -2d, day: \"2DaysAgo\")\navgDay4 = averageWaitingTime(start: -4d, stop: -3d, day: \"3DaysAgo\")\navgDay5 = averageWaitingTime(start: -5d, stop: -4d, day: \"4DaysAgo\")\n\nunion(tables: [avgDay1, avgDay2, avgDay3, avgDay4, avgDay5])\n  |> group()\n  |> pivot(rowKey: [\"media\"], columnKey: [\"day\"], valueColumn: \"mean\")\n  |> yield(name: \"averageWaitingTime5Days\")\n\n"
    }
   ]
  },
  {
   "title": "Current Vehicle Consumption",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"BucketTFG\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"stationA\")\n  |> filter(fn: (r) => contains( value: r[\"name\"], set: ${Chargers:json}))\n  |> filter(fn: (r) => r[\"_field\"] == \"energyConsumed\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: true)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Total Energy Consumed Today",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"BucketTFG\")\n  |> range(start: -1d)  // Ajusta el rango de tiempo según tus necesidades\n  |> filter(fn: (r) => r._measurement == \"stationA\")\n  |> filter(fn: (r) => r._field == \"energyConsumed\" or r._field == \"vehicleID\")\n  |> filter(fn: (r) => contains(value: r[\"name\"], set: ${Chargers:json}))\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> group(columns: [\"name\", \"vehicleID\"])\n  |> sort(columns: [\"_time\"], desc: true)\n  |> unique(column: \"vehicleID\")\n  |> group(columns: [\"name\"])\n  |> sum(column: \"energyConsumed\")\n  |> yield(name: \"totalEnergyConsumedXcharger\")\n"
    }
   ]
  }
 ]
}